const themeLabels: Record<string, string> = {
  andromeeda: '仙女座',
  'aurora-x': '极光 X',
  'ayu-dark': 'Ayu 暗色',
  'catppuccin-frappe': '卡布奇诺·法芙娜',
  'catppuccin-latte': '卡布奇诺·拿铁',
  'catppuccin-macchiato': '卡布奇诺·玛奇朵',
  'catppuccin-mocha': '卡布奇诺·摩卡',
  'dark-plus': '暗色加强',
  dracula: '德古拉',
  'dracula-soft': '德古拉柔和',
  'everforest-dark': '常青林暗色',
  'everforest-light': '常青林亮色',
  'github-dark': 'GitHub 暗色',
  'github-dark-default': 'GitHub 暗色默认',
  'github-dark-dimmed': 'GitHub 暗色柔和',
  'github-dark-high-contrast': 'GitHub 暗色高对比',
  'github-light': 'GitHub 亮色',
  'github-light-default': 'GitHub 亮色默认',
  'github-light-high-contrast': 'GitHub 亮色高对比',
  'gruvbox-dark-hard': 'Gruvbox 暗色硬',
  'gruvbox-dark-medium': 'Gruvbox 暗色中',
  'gruvbox-dark-soft': 'Gruvbox 暗色软',
  'gruvbox-light-hard': 'Gruvbox 亮色硬',
  'gruvbox-light-medium': 'Gruvbox 亮色中',
  'gruvbox-light-soft': 'Gruvbox 亮色软',
  houston: '休斯顿',
  'kanagawa-dragon': '金泽·龙',
  'kanagawa-lotus': '金泽·莲',
  'kanagawa-wave': '金泽·浪',
  laserwave: '激光波',
  'light-plus': '亮色加强',
  'material-theme': 'Material',
  'material-theme-darker': 'Material 更深',
  'material-theme-lighter': 'Material 更浅',
  'material-theme-ocean': 'Material 海洋',
  'material-theme-palenight': 'Material 夜幕',
  'min-dark': '极简暗色',
  'min-light': '极简亮色',
  monokai: '莫诺凯',
  'night-owl': '夜枭',
  nord: '北欧',
  'one-dark-pro': 'One Dark 专业版',
  'one-light': 'One 亮色',
  plastic: '塑料',
  poimandres: '波伊曼德',
  red: '红色',
  'rose-pine': '玫瑰松',
  'rose-pine-dawn': '玫瑰松·黎明',
  'rose-pine-moon': '玫瑰松·月夜',
  'slack-dark': 'Slack 暗色',
  'slack-ochin': 'Slack 浅色',
  'snazzy-light': '时髦亮色',
  'solarized-dark': '日晒暗色',
  'solarized-light': '日晒亮色',
  'synthwave-84': '合成波 84',
  'tokyo-night': '东京夜',
  vesper: '晚祷',
  'vitesse-black': 'Vitesse 纯黑',
  'vitesse-dark': 'Vitesse 暗色',
  'vitesse-light': 'Vitesse 亮色',
}

export function getThemeLabel(themeId: string): string {
  return themeLabels[themeId] || themeId
}
